domain: DOMAIN
apiKey: API-KEY

flags:
  - --dry-run
  - foo=bar

variables:
  greeting: Hello
  name: World

subject: Hello World

recipients:

plain:
  engine: mustache
  path: ./plain.mustache

html:
  engine: mustache
  path: ./html.mustache
