domain: DOMAIN
apiKey: API-KEY

flags:
  - --dry-run
  - foo=bar

from: acme@acme.com
subject: Hello World
to:
cc:
bcc:

variables:
  greeting: Hello
  name: World

plain:
  engine: mustache
  path: ./plain.mustache

html:
  engine: mustache
  path: ./html.mustache
