domain: DOMAIN
apiKey: API-KEY

flags:
  - --subject="Hey World"
  - foo=bar

from: acme@acme.com
subject: Hello World
to:
cc:
bcc:

plain:
  engine: mustache
  path: templates/plain.mustache

html:
  path: templates/html.mustache

variables:
  greeting: Hello
  name: World

