name:                mailgun-cli
version:             0.1.0.0
github:              "tekwrks/mailgun-cli"
license:             BSD3
author:              "tekwrks"
maintainer:          "tekwrks@tekwrks.com"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mailgun-cli#readme>

dependencies:
  - base >= 4.7 && < 5
  - hailgun
  - yaml
  - aeson

library:
  source-dirs: src

executables:
  mailgun-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mailgun-cli

tests:
  mailgun-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mailgun-cli

default-extensions:
  - OverloadedStrings

